version: "3.8"

services:
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
        restart: unless-stopped
        container_name: api
        networks:
            - net
        volumes:
            - ./api:/var/www/html
    nginx:
        image:  nginx:latest
        restart: unless-stopped
        networks:
            - net
        ports:
            - "80:80"
        depends_on:
            - api
        volumes:
            - ./api:/var/www/html
            - ./api/docker/nginx:/etc/nginx
    postgres:
        image: postgres:15-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: termsDb
        networks:
            - net
        depends_on:
            - api
        ports:
            - "5432:5432"
        volumes:
            -  pgadmin-data:/var/lib/postgresql/data
    redis:
        image: redis/redis-stack:latest
        restart: unless-stopped
        networks:
            - net
        depends_on:
            - api
        ports:
            - "6379:6379"
            - "8001:8001"
#    pgadmin:
#        image: dpage/pgadmin4:latest
#        restart: unless-stopped
#        container_name: pgadmin-data
#        networks:
#            - net
#        depends_on:
#            - api
#        environment:
#            PGADMIN_DEFAULT_EMAIL: rajko@vrga.dev
#            PGADMIN_DEFAULT_PASSWORD: root
#        user: root
#        ports:
#            - "5050:80"
networks:
    net:
        driver: bridge

volumes:
    pgadmin-data: