version: "3.8"

services:
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./api:/var/www/html
    nginx:
        image:  nginx:latest
        restart: unless-stopped
        networks:
            - net
        ports:
            - 80:80
        depends_on:
            - api
        volumes:
            - ./api:/var/www/html
            - ./api/docker/nginx/logs:/var/log/nginx
            - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
              POSTGRES_PASSWORD: example
        networks:
            - net
        depends_on:
            - api
        ports:
            - 8081:8081
        volumes:
            - ./api/docker/data/postgres:/var/log/postgresql
    redis:
        image: redis/redis-stack:latest
        restart: unless-stopped
        networks:
            - net
        depends_on:
            - api
        ports:
            - 6379:6379
            - 8001:8001
        volumes:
            - ./api/docker/data/redis:/var/opt/redislabs
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        networks:
            - net
        depends_on:
            - api
        environment:
            PGADMIN_DEFAULT_EMAIL: test@test.com
            PGADMIN_DEFAULT_PASSWORD: test
        ports:
            - 5050:80
        volumes:
            - ./pgadmin-data:/var/lib/pgadmin
networks:
    net:
        driver: bridge